import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SideNavbar from "@/components/SideNavbar";
const home = require("../public/home.jpg");
const square2 = require("../public/square2.jpg");
const square = require("../public/square.jpg");
const star = require("../public/star.jpg");
const profile = require("../public/profile.jpg");
const book = require("../public/book.jpg");

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const images = [
    { src: home, alt: "home", width: 24, height: 24 },
    { src: square2, alt: "square2", width: 24, height: 24 },
    { src: square, alt: "square", width: 24, height: 24 },
    { src: star, alt: "star", width: 24, height: 24 },
    { src: profile, alt: "profile", width: 24, height: 24 },
    { src: book, alt: "book", width: 24, height: 24 },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <SideNavbar images={images} />
        {children}
      </body>
    </html>
  );
}
